import { useEffect, useRef, useState } from 'react';
import { Send, UserPlus } from 'lucide-react';
import { io } from 'socket.io-client';
import api from '../../api/axiosClient';
import { Button, ErrorState, LoadingSpinner } from '../../components/common/UI';
import { useAuth } from '../../contexts/AuthContext';
import { useToast } from '../../contexts/ToastContext';

export default function CommunityPage(){
  const {user}=useAuth();const {notify}=useToast();const [messages,setMessages]=useState(null);const [error,setError]=useState(null);const [reloadKey,setReloadKey]=useState(0);const [text,setText]=useState('');const [username,setUsername]=useState('');const [friends,setFriends]=useState([]);const socketRef=useRef();
  useEffect(()=>{setError(null);Promise.all([api.get('/community/messages/world'),api.get('/community/friends')]).then(([m,f])=>{setMessages(m.data.messages);setFriends(f.data.friendships)}).catch(setError);const root=(import.meta.env.VITE_API_URL||'http://localhost:5000/api').replace(/\/api\/?$/,'');const socket=io(root,{withCredentials:true});socket.on('world:message',(message)=>setMessages(items=>[...(items||[]),message]));socket.on('connect_error',()=>setError(current=>current||new Error('Không thể kết nối kênh chat')));socketRef.current=socket;return()=>socket.disconnect()},[reloadKey]);
  if(error)return <ErrorState message={error.response?.data?.message||error.message} onRetry={()=>{setMessages(null);setReloadKey(value=>value+1)}}/>;
  if(!messages)return <LoadingSpinner/>;
  const send=(e)=>{e.preventDefault();if(!text.trim())return;socketRef.current.emit('world:message',text.trim(),(result)=>{if(!result?.ok)notify('Không gửi được tin nhắn','error')});setText('')};
  const add=async(e)=>{e.preventDefault();try{await api.post('/community/friends',{username});setUsername('');notify('Đã gửi lời mời kết bạn');const {data}=await api.get('/community/friends');setFriends(data.friendships)}catch(err){notify(err.response?.data?.message||'Không thể gửi lời mời','error')}};
  return <section><p className="eyebrow">Cộng đồng</p><h1 className="mt-2 text-3xl font-semibold">Bạn bè & kênh thế giới</h1><div className="mt-8 grid gap-5 xl:grid-cols-[320px_1fr]"><aside className="glass rounded-3xl p-5"><h2 className="font-semibold">Kết nối</h2><form className="mt-4 flex gap-2" onSubmit={add}><input className="input min-w-0" placeholder="Nhập username" value={username} onChange={(e)=>setUsername(e.target.value)}/><Button aria-label="Thêm bạn"><UserPlus size={17}/></Button></form><div className="mt-5 grid gap-2">{friends.map(f=>{const other=f.requester._id===user._id?f.recipient:f.requester;return <div key={f._id} className="rounded-xl bg-white/5 p-3 text-sm"><p>{other.fullName}</p><p className="text-xs text-zinc-500">@{other.username} · {f.status==='accepted'?'Bạn bè':'Đang chờ'}</p>{f.status==='pending'&&f.recipient._id===user._id&&<Button className="mt-2 py-1" variant="ghost" onClick={async()=>{await api.put(`/community/friends/${f._id}`,{accept:true});setFriends(friends.map(x=>x._id===f._id?{...x,status:'accepted'}:x))}}>Chấp nhận</Button>}</div>})}</div></aside><div className="glass flex min-h-[560px] flex-col rounded-3xl p-5"><div className="border-b border-white/10 pb-4"><h2 className="font-semibold"># thế-giới</h2><p className="text-xs text-zinc-500">Trò chuyện realtime cùng mọi người</p></div><div className="flex-1 space-y-4 overflow-y-auto py-5">{messages.map(m=><div key={m._id}><p className="text-xs text-zinc-500">{m.userId?.fullName} <span className="text-violet-400">@{m.userId?.username}</span></p><p className="mt-1 text-sm text-zinc-200">{m.content}</p></div>)}</div><form className="flex gap-2 border-t border-white/10 pt-4" onSubmit={send}><input aria-label="Tin nhắn" className="input" value={text} maxLength="500" onChange={(e)=>setText(e.target.value)} placeholder="Gửi tin nhắn tới thế giới…"/><Button aria-label="Gửi"><Send size={17}/></Button></form></div></div></section>;
}
